# Name: Backstage-analect-io
appId: ${BACK_GITHUB_APP_APP_ID}
webhookUrl: ${BACK_GITHUB_APP_WEBHOOK_URL}
clientId: ${BACK_GITHUB_APP_CLIENT_ID}
clientSecret: ${BACK_GITHUB_APP_CLIENT_SECRET}
webhookSecret: ${BACK_GITHUB_APP_WEBHOOK_SECRET}
privateKey: |
  ${BACK_GITHUB_APP_PRIVATE_KEY}