name: first-release

# env:
#   BACK_GITHUB_APP_APP_ID: ${{ secrets.BACK_GITHUB_APP_APP_ID }}
#   BACK_GITHUB_APP_WEBHOOK_URL: ${{ secrets.BACK_GITHUB_APP_WEBHOOK_URL }}
#   BACK_GITHUB_APP_CLIENT_ID: ${{ secrets.BACK_GITHUB_APP_CLIENT_ID }}
#   BACK_GITHUB_APP_CLIENT_SECRET: ${{ secrets.BACK_GITHUB_APP_CLIENT_SECRET }}
#   BACK_GITHUB_APP_WEBHOOK_SECRET: ${{ secrets.BACK_GITHUB_APP_WEBHOOK_SECRET }}
#   BACK_GITHUB_APP_PRIVATE_KEY: ${{ secrets.BACK_GITHUB_APP_PRIVATE_KEY }}

on:
  workflow_dispatch:


jobs:
  env:
    uses: analect-io/.github/.github/workflows/env.yaml@main

  test:
    uses: analect-io/.github/.github/workflows/test.yaml@main

  quality-gate:
    uses: analect-io/.github/.github/workflows/sonarqube.yaml@main
    secrets: inherit

  docs:
    uses: analect-io/.github/.github/workflows/techdocs.yaml@main
    secrets: inherit
    with:
      repository: ${{ needs.env.outputs.repository }}
    needs:
      - env

  build-and-push:
    uses: analect-io/.github/.github/workflows/build-and-push.yaml@main
    with:
      tag: ${{ needs.env.outputs.tag }}
    needs:
      - env
      - test
      - quality-gate

  security-gateway:
    uses: analect-io/.github/.github/workflows/trivy.yaml@main
    needs:
      - build-and-push

  deploy:
    uses: analect-io/.github/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      tag: ${{ needs.env.outputs.tag }}
      repository: ${{ needs.env.outputs.repository }}
      url: https://${{ needs.env.outputs.repository }}.analect.com
      environment: development
    needs:
      - env
      - security-gateway

  promote:
    uses: analect-io/.github/.github/workflows/promote.yaml@main
    secrets: inherit
    with:
      tag: ${{ needs.env.outputs.tag }}
      repository: ${{ needs.env.outputs.repository }}
      url: https://${{ needs.env.outputs.repository }}.analect.com
      environment: production
    needs:
      - env
      - deploy

  notify:
    uses: analect-io/.github/.github/workflows/notify.yaml@main
    if: always()
    secrets: inherit
    needs:
      - promote